CV2-3086: check file exists
meedan/check-api pull request #1508
Opened 2023-05-07 06:28 UTC by melsawy

2023-05-07 15:38 UTC, caiosba commented
@melsawy please add a description to the PR, otherwise when someone is assigned for review, it's easier to know what's being reviewed.

2023-05-08 18:17 UTC, hartsick commented
Looks like a straightforward fix! A couple of questions / thoughts that came up as I was reviewing:
1. Do we know why the temp file isn't there sometimes? I assume it's just a periodic request and/or write failure that we can't do much about, but curious if you have more context. Is this something worth retrying?
2. Does it make sense to monitor this failure in any way?
3. Is there a test that could be written to catch this case in the future?

2023-05-08 23:22 UTC, caiosba requested changes
Line 155 writes atomically to that file... can we dig more into why it wouldn't exist two lines below? Are we raising an exception and aborting execution if that line fails?

2023-05-09 03:23 UTC, melsawy commented
> 1. Do we know why the temp file isn't there sometimes? I assume it's just a periodic request and/or write failure that we can't do much about, but curious if you have more context. Is this something worth retrying?
I think it's a write failure as this error occurs only one time

> 2. Does it make sense to monitor this failure in any way?
I think yes but @caiosba can confirm

> 3. Is there a test that could be written to catch this case in the future?
No

at the end this failure occurs only one time so I think we should keep an eye on this one in future and do more investigation if got same error

2023-05-09 03:34 UTC, melsawy commented
> Line 155 writes atomically to that file... can we dig more into why it wouldn't exist two lines below? Are we raising an exception and aborting execution if that line fails?

It'll automatically raise an exception if that line fail and this atomically written happens to a tmp directory so may be deleted during deployment for example (as I mention it only one occurs)

2023-05-09 09:51 UTC, caiosba commented
Yes, this likely happened during a deployment...

2023-05-09 20:16 UTC, caiosba approved these changes

2023-05-10 04:44 UTC, merged