CV2-3276: fix Sentry issue
meedan/check-api pull request #1565
Opened 2023-07-11 18:07 UTC by melsawy

## Description

Fix Sentry issue `TypeError: no implicit conversion of String into Integer` related to dig method

`dig` method triggered this error for the cases like this `{a:  []}.dig(:a, :b)` so I rescue the dig and return empty string

References: CV2-3276

## How has this been tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can verify the changes. Please describe whether or not you implemented automated tests.

## Things to pay attention to during code review

Please describe parts of the change that require extra attention during code review, for example:

- File FFFF, line LL: This refactoring does this and this. Is it consistent with how it’s implemented elsewhere?
- Etc.

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have added unit and feature tests, if the PR implements a new feature or otherwise would benefit from additional testing
- [ ] I have added regression tests, if the PR fixes a bug
- [ ] I have added logging, exception reporting, and custom tracing with any additional information required for debugging
- [ ] I have commented my code in hard-to-understand areas, if any
- [ ] I have made needed changes to the README
- [ ] My changes generate no new warnings
- [ ] If I added a third party module, I included a rationale for doing so and followed our current [guidelines](https://meedan.atlassian.net/wiki/spaces/ENG/overview#Choose-the-%E2%80%9Cright%E2%80%9D-3rd-party-module)

2023-07-11 19:22 UTC, caiosba requested changes
@melsawy I'm concerned that this can hide potential changes to WhatsApp payload... I prefer to handle this case specifically.

2023-07-13 16:13 UTC, melsawy commented
@caiosba per our call I found that one will fail when calling is_supported so please  approve the PR and I'll confirm it again on QA

2023-07-13 16:53 UTC, caiosba approved these changes

2023-07-17 03:06 UTC, merged

2023-07-18 00:21 UTC, caiosba commented on app/models/concerns/smooch_capi.rb
> +        ''
@melsawy you missed a unit test for this case :)