CV2-3800: filter feed by organization
meedan/check-api pull request #1703
Opened 2023-10-23 05:47 UTC by melsawy

## Description

Filter feed by organization

References: CV2-3800

## How has this been tested?

Implemented automated tests.

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have added unit and feature tests, if the PR implements a new feature or otherwise would benefit from additional testing
- [ ] I have added regression tests, if the PR fixes a bug
- [ ] I have added logging, exception reporting, and custom tracing with any additional information required for debugging
- [ ] I considered secure coding practices when writing this code. Any security concerns are noted above.
- [ ] I have commented my code in hard-to-understand areas, if any
- [ ] I have made needed changes to the README
- [ ] My changes generate no new warnings
- [ ] If I added a third party module, I included a rationale for doing so and followed our current [guidelines](https://meedan.atlassian.net/wiki/spaces/ENG/overview#Choose-the-%E2%80%9Cright%E2%80%9D-3rd-party-module)

2023-10-23 12:07 UTC, caiosba requested changes
Sawy, I was expecting something simpler... instead of propagating the team filter all the way down until the `Feed` model, can we just apply the filtering in the `team_condition` method in `lib/check_search.rb`? It doesn't matter if other team filters will be included, the team filter should invalidate them anyway.

2023-10-24 14:29 UTC, melsawy commented
yes @caiosba as I found  `get_team_filters` in feed.rb loop in all feed teams and no need to include all teams as we already filtered by specific teams

2023-10-24 14:31 UTC, caiosba commented
> yes @caiosba as I found `get_team_filters` in feed.rb loop in all feed teams and no need to include all teams as we already filtered by specific teams

OK, maybe it will be faster that way.

2023-10-24 14:39 UTC, caiosba approved these changes

2023-10-24 14:54 UTC, merged