CV2-3828 First pass on check api integration updates for audio on alegre
meedan/check-api pull request #1725
Opened 2023-11-10 03:16 UTC by DGaffney

## Description

This work introduces the beginning of a rewrite of the check-api/alegre integration. We do this by using the sync endpoint on alegre, which does an entire store/search loop using presto within a single query. We will continue that pattern through all other modalities, so this ticket is important in conceptually considering the structure of the new code, which, once all modalities are covered, will replace the existing monolith of code that is the check-api/alegre integration.

References: 3828

## How has this been tested?

I've added what I believe are complete, well documented, and representative unit tests for the entire new set of code. I think that its passing 100% right now, but will make sure if its not!

## Things to pay attention to during code review

This code will eventually replace the entire check-api/alegre integration. This should be scrutinized and we should have conversations about whether or not it will be extensible, whether or not it will be easier to work with, and what sorts of business logic it may disrupt. please pick it apart!

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have added unit and feature tests, if the PR implements a new feature or otherwise would benefit from additional testing
- [ ] I have added regression tests, if the PR fixes a bug
- [ ] I have added logging, exception reporting, and custom tracing with any additional information required for debugging
- [ ] I considered secure coding practices when writing this code. Any security concerns are noted above.
- [ ] I have commented my code in hard-to-understand areas, if any
- [ ] I have made needed changes to the README
- [ ] My changes generate no new warnings
- [ ] If I added a third party module, I included a rationale for doing so and followed our current [guidelines](https://meedan.atlassian.net/wiki/spaces/ENG/overview#Choose-the-%E2%80%9Cright%E2%80%9D-3rd-party-module)

2023-11-11 07:28 UTC, melsawy commented
@DGaffney please fix Code Climate(CC) issues and Travis tests so I can start the review

2023-11-11 07:29 UTC, melsawy requested changes
@DGaffney please fix Code Climate(CC) issues and Travis tests so I can start the review

2023-11-15 15:24 UTC, caiosba commented
@DGaffney let us know please when integration tests are passing for this branch.

2023-11-21 20:28 UTC, caiosba requested changes
Code looks good overall! I tested the branch locally with the following features:

- [x] NLU
- [x] Text similarity matching
- [x] Tipline text similarity search

All of that worked well. @DGaffney , I just have two questions:

(1) [These lines](https://github.com/meedan/check-api/blob/cv2-3828-audio-update/app/models/concerns/alegre_v2.rb#L45-L49) are not covered by the tests, which I think is actually a good thing and a confirmation that all requests from Check API are now using POST instead of GET? If you confirm, can we delete those lines of code?

(2) The method `get_context` is defined in two different places, [here](https://github.com/meedan/check-api/blob/cv2-3828-audio-update/app/models/concerns/alegre_v2.rb#L149) and [here](https://github.com/meedan/check-api/blob/cv2-3828-audio-update/app/models/concerns/alegre_similarity.rb#L120), but both modules are included by the same class. Can we remove one of the two then? According to the coverage report, the one being called is the one in `alegre_v2.rb`, and the one in `alegre_similarity.rb` is being ignored - please review which one should stay since they are slightly different.

2023-11-21 21:41 UTC, DGaffney commented
> Code looks good overall! I tested the branch locally with the following features:
> 
> * [x]  NLU
> * [x]  Text similarity matching
> * [x]  Tipline text similarity search
> 
> All of that worked well. @DGaffney , I just have two questions:
> 
> (1) [These lines](https://github.com/meedan/check-api/blob/cv2-3828-audio-update/app/models/concerns/alegre_v2.rb#L45-L49) are not covered by the tests, which I think is actually a good thing and a confirmation that all requests from Check API are now using POST instead of GET? If you confirm, can we delete those lines of code?
> 
> (2) The method `get_context` is defined in two different places, [here](https://github.com/meedan/check-api/blob/cv2-3828-audio-update/app/models/concerns/alegre_v2.rb#L149) and [here](https://github.com/meedan/check-api/blob/cv2-3828-audio-update/app/models/concerns/alegre_similarity.rb#L120), but both modules are included by the same class. Can we remove one of the two then? According to the coverage report, the one being called is the one in `alegre_v2.rb`, and the one in `alegre_similarity.rb` is being ignored - please review which one should stay since they are slightly different.

Good points on both cases! I've modified to accommodate. Thank you!

2023-11-22 15:44 UTC, caiosba approved these changes
Thanks Devin for addressing the review comments!

2023-11-27 14:19 UTC, merged