3994 – Improve seeds file: add variation to requests
meedan/check-api pull request #1735
Opened 2023-11-21 20:38 UTC by vasconsaurus

## Description

Add some variation to tipline requests as per Brian's (request)[https://github.com/meedan/check-api/pull/1723#issuecomment-1802465942]

References: 3994

## How has this been tested?

Ran the seeds script to create an user, and to add data to the same user.

2023-11-21 20:40 UTC, vasconsaurus commented
@brianfleming another one for you to take a look. I think it's the last one (for now) 🎉

2023-11-22 16:03 UTC, brianfleming commented
So good @vasconsaurus I ran it, and now I see so much great stuff!

![power](https://github.com/meedan/check-api/assets/418001/4018b3e2-6000-4250-9dd3-5b148611edf5)

2023-11-22 16:31 UTC, caiosba requested changes
Great stuff Manu, I just added two comments. One more note: we're using `sample` in a few places, which means that we won't necessarily get at least of example of each type (status, request links, request channel, etc.). I think it's fine for now, just noting that this is something we may change in the future if we really need to have at least one example of each type.

2023-11-22 16:31 UTC, caiosba commented on db/seeds.rb
> +    image: 'https://media.smooch.io/apps/5c193e2380a9c90022e40b86/conversations/d445678ac87d2e9f44485e40/sUn5Sq9xRiacbV0Af2qmjl5G/bOoeoeV9zNA51ecial0eWDG6.jpeg',
Please replace these by fake URLs (we're moving out of Smooch anyway). The important bit here is just the file extensions, but the URLs don't need to be real.

2023-11-22 16:31 UTC, caiosba commented on db/seeds.rb
> +
Trailing white space :)

2023-11-22 17:55 UTC, caiosba approved these changes

2023-11-22 18:04 UTC, merged