Tipline history pagination
meedan/check-api pull request #1745
Opened 2023-11-29 18:14 UTC by dariusk

I had to add an optional `external_id` filter to the `tipline_messages` function. This is required because I need to be able to associate `TiplineRequest` with `TiplineMessages` and I can't derive a cursor value for `TiplineMessages` from `TiplineRequest` because it's a totally different object so graphql wouldn't track that. The `value_json` in `TiplineRequest` contains a reference to `_id` which matches `external_id` on `TiplineMessages`. This lets me do a filter like the following, where `externalId` is derived from `TiplineRequest` is derived from `ProjectMedia`:

```graphql
tipline_messages(uid:"abc123",externalId:"def456") {
    edges {
      node {
        cursor
        dbid,
      }
    }
}
```

Things to consider:

 - not sure I did this correctly, please let me know
 - I don't understand why rails removed the index on `external_id` -- seems like we would want it since we are searching by it?

2023-11-29 18:22 UTC, caiosba requested changes
Looks good to me overall! Yeah, I don't understand why Rails updated your `schema.rb`... this is generated based on your current local database, so maybe you have an old database locally. Please revert that, this is only needed when a database migration is added.

Also, please run `docker-compose run api bundle exec rake lapis:graphql:schema` and push the updated `public/relay.json` and `lib/realy.idl` (actually, Check Web won't be able to use the new argument until `relay.json` is updated).

2023-11-29 20:50 UTC, caiosba approved these changes
Looks good! I just added a test for this new case: https://github.com/meedan/check-api/pull/1745/commits/28f70bca1f53ad33068901dd18a37ba6ef4a676a.

This is good to go once the frontend is implemented.

@melsawy please review too.

2023-12-03 04:37 UTC, melsawy commented on app/graph/types/team_type.rb
> +    end
we can simplify this one to be 
```
conditions = { uid:  uid }
conditions[:external_id] = external_id unless external_id.blank?
TiplineMessagesPagination.new(object.tipline_messages.where(conditions).order('id ASC'))
```

2023-12-03 04:39 UTC, melsawy approved these changes
Looks good!  just leave one comment to simplify `tipline_messages` method

2024-05-22 23:00 UTC, closed without merging