CV2-4072: use PublicTeamType instead of TeamType
meedan/check-api pull request #1770
Opened 2024-01-03 12:37 UTC by melsawy

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context – why has this been changed/fixed.

References: TICKET-ID, TICKET-ID, …

## How has this been tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can verify the changes. Please describe whether or not you implemented automated tests.

## Things to pay attention to during code review

Please describe parts of the change that require extra attention during code review, for example:

- File FFFF, line LL: This refactoring does this and this. Is it consistent with how it’s implemented elsewhere?
- Etc.

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have added unit and feature tests, if the PR implements a new feature or otherwise would benefit from additional testing
- [ ] I have added regression tests, if the PR fixes a bug
- [ ] I have added logging, exception reporting, and custom tracing with any additional information required for debugging
- [ ] I considered secure coding practices when writing this code. Any security concerns are noted above.
- [ ] I have commented my code in hard-to-understand areas, if any
- [ ] I have made needed changes to the README
- [ ] My changes generate no new warnings
- [ ] If I added a third party module, I included a rationale for doing so and followed our current [guidelines](https://meedan.atlassian.net/wiki/spaces/ENG/overview#Choose-the-%E2%80%9Cright%E2%80%9D-3rd-party-module)

2024-01-16 13:40 UTC, caiosba requested changes
Thanks Sawy, I just noticed one more case: `team_author` in `BotUserType` should be `PublicTeamType` too. After this fix, fixes for the tests and changes on Check Web side, I think this is good to go :)

2024-01-30 16:44 UTC, caiosba commented
@melsawy also, please be sure it works on the Check Web side, specially with feed features - @danielevalverde can help you with testing this if needed.

2024-01-30 16:57 UTC, melsawy commented on app/models/user.rb
> +    self
yes @caiosba makes sense and as you know I used this one as a return value for `updateUser` mutation so it'll return a value when current user did  update action.

2024-01-31 05:55 UTC, melsawy commented on app/models/user.rb
> +    self
Done

2024-01-31 06:00 UTC, melsawy commented
@caiosba Already I tested the app locally especially features related to changed files.
also I back `medias_count` field to `PublicTeamType` with same way as other count fields like `trash_count`, `unconfirmed_count`, etc as without this field the item does not appear on item page immediately and require a page refresh as the item still assigned to a default project by default.
I think we can review these fields later after deprecate folders from the back-end

2024-01-31 14:09 UTC, caiosba approved these changes

2024-02-01 07:17 UTC, merged