Epic/cv2-3939: replace table view with cards
meedan/check-api pull request #1924
Opened 2024-06-12 14:55 UTC by danielevalverde

## Description

 Expose  projectMedia.fact_check_published_on field
References: CV2-3929

## Things to pay attention to during code review

Please describe parts of the change that require extra attention during code review, for example:

- File FFFF, line LL: This refactoring does this and this. Is it consistent with how it’s implemented elsewhere?
- Etc.

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have added unit and feature tests, if the PR implements a new feature or otherwise would benefit from additional testing
- [ ] I have added regression tests, if the PR fixes a bug
- [ ] I have added logging, exception reporting, and custom tracing with any additional information required for debugging
- [ ] I considered secure coding practices when writing this code. Any security concerns are noted above.
- [ ] I have commented my code in hard-to-understand areas, if any
- [ ] I have made needed changes to the README
- [ ] My changes generate no new warnings
- [ ] If I added a third party module, I included a rationale for doing so and followed our current [guidelines](https://meedan.atlassian.net/wiki/spaces/ENG/overview#Choose-the-%E2%80%9Cright%E2%80%9D-3rd-party-module)

2024-06-12 15:28 UTC, danielevalverde commented
> We just merged this, no? :D
> 
> [8188030](https://github.com/meedan/check-api/commit/81880302c2ee84e68195c55892f15082224e54d0)

Thanks, @caiosba  :)
I updated with develop now

2024-06-12 15:29 UTC, caiosba commented
So there is nothing left here - can we close, then?

2024-06-12 15:37 UTC, amoedoamorim commented
> So there is nothing left here - can we close, then?

There's Dani's PR agains the epic branch, then we'll merge the epic branch, but that's just leading to double reviewing the same stuff since I've already merged the other changes :shrug:

2024-06-12 15:39 UTC, caiosba commented
I just clarified with @danielevalverde - yes, this is the epic branch, let's keep it.

2024-06-25 21:08 UTC, brianfleming commented
this can/should be merged now too right @danielevalverde and @amoedoamorim ?

2024-07-02 13:00 UTC, brianfleming commented
> this can/should be merged now too right @danielevalverde and @amoedoamorim ?

any reply to my question @danielevalverde or @amoedoamorim ? Asking because I notice the graphql warnings left in the output about the old pages

2024-07-03 14:48 UTC, caiosba requested changes
Dani, please check my comments but also:

1) Be sure it's up-to-date with latest `develop`
2) Run integration tests against this branch

2024-07-03 14:48 UTC, caiosba commented on app/graph/types/team_type.rb
> +  field :get_data_report_url, GraphQL::Types::String, null: true
This is duplicating line 115

2024-07-03 14:48 UTC, caiosba commented on db/seeds.rb
These changes seem unrelated... maybe you need to rebase with `develop`?

2024-07-03 19:35 UTC, caiosba requested changes

2024-07-03 19:35 UTC, caiosba commented on app/models/concerns/team_duplication.rb
>        team_task_map = self.team_task_map
@danielevalverde you can delete this line too

2024-07-04 16:53 UTC, caiosba requested changes
@danielevalverde I have good news and bad news.

Bad news: I didn't pay attention to the code coverage report before, so there is still a bit more work to be done here.

Good news: We have more lines of code to be deleted! :tada: 

According to the [coverage report](https://app.travis-ci.com/github/meedan/check-api/jobs/623712490#L4515), we can delete:

```
app/models/concerns/project_media_getters.rb: 76
lib/check_search.rb: 529, 531, 536
```

- This method, which is not used anywhere anymore: https://github.com/meedan/check-api/blob/epic/cv2-3939-replace-table-view-with-cards/app/models/concerns/project_media_getters.rb#L75-L77
- This whole block, since we don't sort by tasks on the frontend side anymore: https://github.com/meedan/check-api/blob/epic/cv2-3939-replace-table-view-with-cards/lib/check_search.rb#L526-L552

2024-07-04 16:57 UTC, caiosba requested changes

2024-07-04 16:57 UTC, caiosba commented on lib/check_search.rb
> -    elsif SORT_MAPPING.keys.include?(@options['sort'].to_s)
Please keep this line but change the `elsif` by `if`.

2024-07-04 16:58 UTC, caiosba approved these changes
Thanks Dani!

2024-07-04 18:36 UTC, merged