CV2-5628: fix OR condition and remove projects filter
meedan/check-api pull request #2125
Opened 2024-11-11 09:59 UTC by melsawy

## Description

Remove projects filter and fix `OR` conditions .
- [ ] Revisit ES `OR` conditions
- [ ] Remove `projects` filter

References: CV2-5628

## How has this been tested?

Re-run  automated tests.

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have added unit and feature tests, if the PR implements a new feature or otherwise would benefit from additional testing
- [ ] I have added regression tests, if the PR fixes a bug
- [ ] I have added logging, exception reporting, and custom tracing with any additional information required for debugging
- [ ] I considered secure coding practices when writing this code. Any security concerns are noted above.
- [ ] I have commented my code in hard-to-understand areas, if any
- [ ] I have made needed changes to the README
- [ ] My changes generate no new warnings
- [ ] If I added a third party module, I included a rationale for doing so and followed our current [guidelines](https://meedan.atlassian.net/wiki/spaces/ENG/overview#Choose-the-%E2%80%9Cright%E2%80%9D-3rd-party-module)

2024-11-13 20:47 UTC, melsawy commented on lib/check_search.rb
> +      custom_conditions.concat team_tasks_conditions
Yes @caiosba just move the block under `unless`

2024-11-13 20:49 UTC, melsawy commented on lib/check_search.rb
> -  end
Good idea to make sure we always have a workspace filter

2024-11-20 04:40 UTC, melsawy commented on lib/check_search.rb
> -  end
@caiosba we already set a team filter and also return `[ProjectMedia.none` if the team filter is blank](url) so no need to add extra work for team filter

2024-11-20 13:25 UTC, caiosba requested changes
Sawy, please add the `adjust_team_work` to replace the `adjust_project_filter`, as we discussed.

2024-11-20 14:32 UTC, melsawy commented
> Sawy, please add the `adjust_team_filter` method to replace the `adjust_project_filter` method you removed, as we discussed.

@caiosba already I found a [team_conditions methos](https://github.com/meedan/check-api/blob/develop/lib/check_search.rb#L72-L80) which do the same things and medias method return `ProjectMedia.none` if the the team filter is black so I think this is OK, what do you think?

2024-11-20 16:01 UTC, caiosba commented
> > Sawy, please add the `adjust_team_filter` method to replace the `adjust_project_filter` method you removed, as we discussed.
> 
> @caiosba already I found a [team_conditions methos](https://github.com/meedan/check-api/blob/develop/lib/check_search.rb#L72-L80) which do the same things and medias method return `ProjectMedia.none` if the the team filter is black so I think this is OK, what do you think?

This is just returning the team values, I think it's important to make sure it's always part of the query.

2024-11-20 16:21 UTC, melsawy commented
> > > Sawy, please add the `adjust_team_filter` method to replace the `adjust_project_filter` method you removed, as we discussed.
> > 
> > 
> > @caiosba already I found a [team_conditions methos](https://github.com/meedan/check-api/blob/develop/lib/check_search.rb#L72-L80) which do the same things and medias method return `ProjectMedia.none` if the the team filter is black so I think this is OK, what do you think?
> 
> This is just returning the team values, I think it's important to make sure it's always part of the query.

yes it's always part of the query either PG or ES

2024-11-21 13:41 UTC, caiosba approved these changes

2024-12-10 19:41 UTC, merged